/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bundleUnpack;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    /* gradle init 选 1. Junit4 自动生成的，范例。请勿删除！！！
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    */

    @Test public void testBundlesInit() {
        BundleS classUnderTest = new BundleS("cfg/setBundles.cfg");
        assert(classUnderTest.initBundles()==3);

        assert(classUnderTest.placeOrder("IMG", 2).getTotalPrice() < 450+1);

        //...继续测试其他 方法 
    }
}
