/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ade.lisa.challenge;


import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testReadWriteOrder() {
        FileReadWrite classUnderTest = new FileReadWrite();
        classUnderTest.readOrder();
        assertEquals(classUnderTest.readOrder().getItemList().size(), 5);
    }
    @Test public void testReadWrite() {
        FileReadWrite classUnderTest = new FileReadWrite();
        classUnderTest.readBundleFormat();
        assertEquals(classUnderTest.readBundleFormat().size(), 3);
    }
}
