/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bundle_unpack;


import java.util.Map;

public class App {
    public static void main(String[] args) {
        FileReadWrite rwTool = new FileReadWrite();
        Map<String, Bundle> bundleCalMap = rwTool.readBundleFormat();
        //get order info 
        Order order = rwTool.readOrder();
        BundleProcess process = new BundleProcess();
        OrderResult outputBD = process.placeOrder(order, bundleCalMap);
        rwTool.printOrderResult(order, outputBD);
    }
}