/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bundleUnpack;

import java.io.IOException;
import java.util.HashMap;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;


/** Given a brands order, determine the cost and bundle breakdown for each submission format.
 *  Budles： 
 *  IMG     5 @ $450 10 @ $800
 *  FLAC    3 @ $427.50 6 @ $810 9 @ $1147.50
 *  VID     3 @ $570 5 @ $900 9 @ $1530
 *  
 * Input：
 *          10 IMG
 *          15 FLAC
 *          13 VID
 * 
 * Output：
 *          10 IMG $800 --   1 x 10 $800
 *          15 FLAC $1957.50 -- 1 x 9 $1147.50 +  1 x 6 $810
 *          13 VID $2370 --   2 x 5 $1800 + 1 x 3 $570
 */
public class App{

    public static void main(String[] args) {
        
        Logger logger = Logger.getLogger("LoggerLog");

        logger.setLevel(Level.INFO);

        try {
            //add fileHandler
            FileHandler fileHandler = new FileHandler("log/logMain.log");
            fileHandler.setLevel(Level.INFO); 
            fileHandler.setFormatter(new MyFormat());

            //add fileHandler to logger
            logger.addHandler(fileHandler);
            
        } catch (SecurityException | IOException e) {
            e.printStackTrace();
        }
 
        //用配置文件名称 初始化 Bundles 对象
        BundleS bs = new BundleS("cfg/setBundles.cfg");
        logger.info("从文件 setBundles.log 获取：产品类型 及 Bundle 分包价格 信息");
       
        HashMap<String, Integer> targetNums = new HashMap<String, Integer>();
        //添加键值对
        targetNums.put("IMG", 10);
        targetNums.put("FLAC", 15);
        targetNums.put("VID", 4);

        targetNums.forEach((key, value) -> {
            logger.info("\t下单：" + key + " " + value + " 件");
            double prc = bs.placeOrder(key, value);
            logger.info("\t----花费：" + prc);
        });
    }
}